### ISSUE TITLE
Parsing fails on valid input

### ISSUE THREAD

**Issue by centromere** [sol/doctest#101]
Place this in test.hs:
```
data Test = Test {
  test :: ByteString
       -- ^ blah
       -> ByteString
}
```
Then run doctest on it:
```
$ doctest test.hs 

test.hs:4:8: parse error on input `->'
```

```
$ doctest --version
doctest version 0.9.12
using version 7.6.3 of the GHC API
using /usr/lib/ghc/bin/ghc-7.6.3
```

**Comment by sol** [comment]
This is not a bug in doctest, but rather a limitation in GHC/Haddock.  Haddock comments are currently not allowed at that position.

You should be able to verify this by trying to generate Haddock documentation for that code.  This should fail, too.

If you want this to work, you could open a feature request for GHC/Haddock.
