### ISSUE TITLE
GHC 7.12

### ISSUE THREAD

**Issue by kazu-yamamoto** [sol/doctest#114]
Testing a package with GHC head (7.12) on Travis CI, I got the following error:

```
expected: Just (HTTPDate {hdYear = 1994, hdMonth = 11, hdDay = 15, hdHour = 8, hdMinute = 12, hdSecond = 31, hdWkday = 2})

 but got: Just HTTPDate {hdYear = 1994, hdMonth = 11, hdDay = 15, hdHour = 8, hdMinute = 12, hdSecond = 31, hdWkday = 2}
```

I was really surprised. Is this a bug of GHC pretty printer?

**Comment by soenkehahn** [comment]
I was really surprised too. :) Turns out the new version is completely valid Haskell and equivalent to the old version. So apparently the pretty-printer behaviour just changed.

**Comment by kazu-yamamoto** [comment]
I heard that this is an intentional change: https://ghc.haskell.org/trac/ghc/ticket/2530

**Comment by kazu-yamamoto** [comment]
@sol Do you have any dieas to allow both styles in doctest?

**Comment by sol** [comment]
Hmm, not sure

**Comment by RyanGlScott** [comment]
FWIW, that `Show` behavior has [since been reverted](https://ghc.haskell.org/trac/ghc/ticket/2530#comment:39), so it should go back to displaying the redundant parentheses.

**Comment by andreasabel** [comment]
Seems like this issue can be closed?!

**Comment by sol** [comment]
@andreasabel Yes, I guess.
