### ISSUE TITLE
Can't import Test.QuickCheck

### ISSUE THREAD

**Issue by edliaw** [sol/doctest#115]
I'm using GHC 7.10.2, installed using nix with QuickCheck-2.8.1 and doctest-0.10.1.  I verified that the packages are installed by running ghc-pkg list.

Running the following minimal example with doctest:

    module Check where
    -- $setup
    -- >>> import Test.QuickCheck

Gave me the following error:

    ### Failure in check.hs:4: expression `import Test.QuickCheck'
    expected:
     but got:
              <no location info>:
                  Could not find module ‘Test.QuickCheck’
                  It is not a module in the current program, or in any known package.
    Examples: 1  Tried: 1  Errors: 0  Failures: 1

I'm trying to figure out why this is happening now, but it would be helpful if someone using 7.10.2 could also check whether this works or not.

**Comment by sol** [comment]
@peti Do you know whether this is a nix issue?

**Comment by peti** [comment]
Yes, this phenomenon is specific to Nix. It sounds like the `$NIX_GHC*` environment variables aren't set up properly. @edliaw, see http://nixos.org/nixpkgs/manual/#how-to-install-a-compiler-with-libraries for details.

**Comment by edliaw** [comment]
Thanks @peti, that was the problem.  Got it working now.
