### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by flip111** [sol/doctest#120]
I was using haskell platform with cabal before, now i removed all of this and start over with stack. How can i use this library with stack?

**Comment by flip111** [comment]
I found it:
```
stack install doctest
```

then add `~/.local/bin` to path
make sure your file has a main function (don't know why this is important, but needed anyway)
then just type `doctest`
or you can type `stack exec doctest -- File.hs`

**Comment by lwm** [comment]
@flip111 - Nice. You can probably close this issue off then :+1:

**Comment by flip111** [comment]
Will do :)
