### ISSUE TITLE
Disregard whitespace

### ISSUE THREAD

**Issue by flip111** [sol/doctest#121]
i have this test

``` haskell
-- |
-- >>> insertElem ([], [])    2
-- ([2]    , [])
```

and i get

```
» doctest Main.hs
### Failure in Main.hs:50: expression `insertElem ([], [])    2'
expected: ([2]    , [])
 but got: ([2],[])
Examples: 1  Tried: 1  Errors: 0  Failures: 1
```

How can i let doctest ignore whitespace so that it will evaluate that `([2],[])` is the same as `([2]    , [])` ??

**Comment by cheecheeo** [comment]
@flip111 A workaround for this is to write:
```
-- |
-- >>> insertElem ([], [])    2 == ([2]    , [])
-- True
```

When I looked into the feature set of doctest in the original python implementation this "ignoring" whitespace was considered a misfeature as doctest's stated goal is to compare what you would get from the REPL/ghci with what's in your doctest. Similar reasoning applies to Haskell's doctest.

In the case of:
```
-- |
-- >>> putStrLn "   hello world"
--    hello world
```
Ignoring the whitespace in the expected result would be incorrect.

**Comment by flip111** [comment]
oh i thought it was comparing days structures, but actually it's just comparing strings???

**Comment by cheecheeo** [comment]
@flip111 Yes. The way to think about doctest is "If I wrote this in the REPL/ghci what is the exact output that it would return?" This is how it works with IO computations like `putStrLn` for example.

**Comment by lwm** [comment]
@flip111, you can probably close this one off.

**Comment by andreasabel** [comment]
Same as #138.

**Comment by rampion** [comment]
My workaround is to use `pretty-show` to make my test outputs more legible. This doesn't make the comparison whitespace-agnostic, but it can make the result of a test far more legible, which, for me, is the whole reason I wanted to include more whitespace to begin with.

For example this test's output is a little hard for a human to quickly read:

```haskell
-- |
-- >>> indexTest "Hello"
-- Env {paragraphs = [(0,0)], sentences = [(0,0)], words = [(0,4)], chars = "Hello", numParagraphs = 1, numSentences = 1, numWords = 1, numChars = 5}
```

But if I switch the interpreter's print function to use `pPrint` from `pretty-show`,

```haskell
-- $setup
-- >>> import Text.Show.Pretty (pPrint)
-- >>> :set -interactive-print pPrint
```

I get an example that's much easier on the eyes:

```haskell
-- |
-- >>> indexText "Hello"
-- Env
--   { paragraphs = [ ( 0 , 0 ) ]
--   , sentences = [ ( 0 , 0 ) ]
--   , words = [ ( 0 , 4 ) ]
--   , chars = "Hello"
--   , numParagraphs = 1
--   , numSentences = 1
--   , numWords = 1
--   , numChars = 5
--   }
```
