### ISSUE TITLE
Module requirement?

### ISSUE THREAD

**Issue by flip111** [sol/doctest#124]
I noticed i either have to put something like `module Foo where` or `main = putStrLn "dummy"` for the doctest to run. Otherwise i get `Foo.hs:1:1: The IO action ‘main’ is not defined in module ‘Main’`. Can i use doctest for just prototyping some functions without diving into modules?

**Comment by soenkehahn** [comment]
In Haskell every file is a module. If you have a module header (e.g. `module Foo where`) then the module is named `Foo`. If you omit the module header the module will be assumed to be the `Main` module by default. But then it needs a `main` function.

So this is rather a Haskell (or ghc) requirement than a doctest thing.
