### ISSUE TITLE
Bug: Tuples are not compared correctly

### ISSUE THREAD

**Issue by fabianhjr** [sol/doctest#138]
```
> doctest src/Complex.hs                       Sat 20 Aug 2016 03:32:03 PM CDT
### Failure in src/Complex.hs:51: expression `sum (1, 0) (0, 1)'
expected: (1.0, 1.0)
 but got: (1.0,1.0)
```

Notice the empty space? If I remove it then it passes

``` haskell
-- >>> sum (1, 0) (0, 1)
-- (1.0, 1.0)
sum :: (Double, Double) -> (Double, Double) -> (Double, Double)
sum (a1, b1) (a2, b2) = (a1 + a2, b1 + b2)
```

EDIT: As @sol mentioned, this is an issue on how doctest compares stuff. (String and String equality)

**Comment by sol** [comment]
Doctest does string based comparison. So this is a restriction on how doctest works. I don't see an easy way to lift this restriction.

**Comment by fabianhjr** [comment]
Will look into it, if I find a way to do some basic comparison then I will open a PR.

**Comment by andreasabel** [comment]
I suppose this issue can be closed.

**Comment by flip111** [comment]
what about adding an option to doctest that will do a `read` on the string before comparison? Seems not difficult to implement, i know that won't probably work in all cases but that's up the user then

**Comment by sol** [comment]
@flip111 To use `read` you would need to decide on a concrete result type.  How would you imagine `doctest` to make that decision?

**Comment by flip111** [comment]
I would leave that part up to the user

**Comment by sol** [comment]
@flip111 how exactly would a user provided that information?

**Comment by flip111** [comment]
I don't have a preference for that .. but if you need an idea maybe something can be done with those 3 `>>>`.

**Comment by sol** [comment]
It may indeed be possible to do something here, even without the user providing any additional information.

Doctest could probe the type of the expression with `:t`, then try a `show . read`.  If that succeeds, it could use resulting string for comparison.

Still not sure if that is a good idea, but I think it wold work.
