### ISSUE TITLE
Different naming on report?

### ISSUE THREAD

**Issue by lwm** [sol/doctest#139]
Would you accept a PR for the following changes:

```
Examples: 2  Tried: 2  Errors: 0  Failures: 1
```

Would become:

```
Found: 2  Successful: 2  Errors: 0  Failures: 1
```

Where `Examples -> Found` and `Tried -> Successful`.

Possibly nitpicking!

**Comment by sol** [comment]
I don't particularly like the current output, but changing it is a breaking change.

I would be happy to change it as we approach 1.0, together with a general formatter overhaul. In that case I would want to use something that is close to what hspec uses.

However, currently I don't have many cycles to burn, and it's not at the top of my list of priorities.

**Comment by lwm** [comment]
> I would be happy to change it as we approach 1.0, together with a general formatter overhaul. In that case I would want to use something that is close to what hspec uses.

So, great. I leave it in your capable hands!
