### ISSUE TITLE
Lexical error on #import, etc.

### ISSUE THREAD

**Issue by ExcaliburZero** [sol/doctest#140]
Currently when doctest is given a source file that contains something like `#include "HsConfigure.h"` or `#if LANGUAGE_Rank2Types` it yields a lexical error.

To reproduce this issue you can try running doctest on the `Data.Time.Calendar.Days` module in the time package.

```
$ git clone git@github.com:haskell/time.git
$ cd time
$ doctest lib/Data/Time/Calendar/Days.hs

lib/Data/Time/Calendar/Days.hs:2:2: lexical error at character 'i'
```

**Comment by sol** [comment]
You need to invoke doctest with the correct set of command-line flags.

Try to get it working with ghci first, then invoke doctest with the exact same set of command-line flags.

Hope that helps.

**Comment by ExcaliburZero** [comment]
@sol 

I took a look over the ghci help info and found that using the `-cpp` flag allows ghci to work with files that use things like `#include`.

I tried using doctest with the `-cpp` flag on the file, and it did not yield the lexical error.

Thanks for the help!
