### ISSUE TITLE
Doctests need a long time to start

### ISSUE THREAD

**Issue by minad** [sol/doctest#141]
Hi,

it seems to me that much time of the doctests is needed for startup and library loading. Would it be possible to generate or cache doctest hs files e.g. in src/doctest which could then be compiled as usual by cabal/ghc? This way one could take advantage of the ghc dependency checking.

Maybe there is a better way?

Thx for the tool!

Daniel

**Comment by minad** [comment]
Together with your hpack tool this could be very useful I guess since one would just have to specify the directory of the generated doctests for auto discovery. The main of the autogenerated tests could then regenerate or at least fail if the cached tests were outdated.

**Comment by sjakobi** [comment]
I have profiled a doctest run that usually takes about 17s with `stack test --profile :doctest`. You can find the .prof file together with the code [here](https://github.com/sjakobi/vgrep/blob/prof/doctest.prof).

**Comment by simonmichael** [comment]
Another data point: `stack test hledger-lib:test:doctests` takes about 40s to run 106 doctest examples on a 2013 macbook air. 15-20s before it shows the first tests being run.
