### ISSUE TITLE
unterminated multiline error occured in GHC8.01

### ISSUE THREAD

**Issue by cutsea110** [sol/doctest#142]
Hi

I've got an error `unterminated multiline command' in GHC 8.0.1.
The test code has been passed at 7.10.* and doctest 0.11

The error messages are below.

<pre>
>>= cabal clean && cabal configure --user --enable-tests && cabal build && cabal test
cleaning...
Resolving dependencies...
Configuring heredocs-0.1.4...
Building heredocs-0.1.4...
Preprocessing library heredocs-0.1.4...
[1 of 1] Compiling Text.Heredoc     ( src/Text/Heredoc.hs, dist/build/Text/Heredoc.o )
Preprocessing test suite 'doctest' for heredocs-0.1.4...
[1 of 1] Compiling Main             ( test/doctests.hs, dist/build/doctest/doctest-tmp/Main.o )
Linking dist/build/doctest/doctest ...
Preprocessing library heredocs-0.1.4...
Preprocessing test suite 'doctest' for heredocs-0.1.4...
Running 1 test suites...
Test suite doctest: RUNNING...
### Error in test/Test.hs:60: expression `:{'
unterminated multiline command
### Error in test/Test.hs:72: expression `:{'
unterminated multiline command
### Error in test/Test.hs:84: expression `:{'
unterminated multiline command
### Error in test/Test.hs:94: expression `:{'
unterminated multiline command
### Error in test/Test.hs:106: expression `:{'
unterminated multiline command
### Error in test/Test.hs:120: expression `:{'
unterminated multiline command
### Error in test/Test.hs:131: expression `:{'
unterminated multiline command
### Error in test/Test.hs:140: expression `:{'
unterminated multiline command
### Error in test/Test.hs:149: expression `:{'
unterminated multiline command
### Error in test/Test.hs:203: expression `:{'
unterminated multiline command
### Error in test/Test.hs:214: expression `:{'
unterminated multiline command
### Failure in test/Test.hs:229: expression `data Person = Person String Int Gender deriving Show'
expected:
 but got:
          <interactive>:143:33: error:
              Not in scope: type constructor or class ‘Gender’
### Error in test/Test.hs:246: expression `:{'
unterminated multiline command
### Error in test/Test.hs:257: expression `:{'
unterminated multiline command
### Error in test/Test.hs:269: expression `:{'
unterminated multiline command
### Error in test/Test.hs:278: expression `:{'
unterminated multiline command
### Error in test/Test.hs:287: expression `:{'
unterminated multiline command
### Error in test/Test.hs:298: expression `:{'
unterminated multiline command
### Error in test/Test.hs:307: expression `:{'
unterminated multiline command
### Error in test/Test.hs:316: expression `:{'
unterminated multiline command
### Failure in test/Test.hs:325: expression `data Person' = Person' { name :: String, age :: Int, sex :: Gender }'
expected:
 but got:
          <interactive>:181:61: error:
              Not in scope: type constructor or class ‘Gender’
### Error in test/Test.hs:348: expression `:{'
unterminated multiline command
Examples: 41  Tried: 39  Errors: 20  Failures: 2
Test suite doctest: FAIL
Test suite logged to: dist/test/heredocs-0.1.4-doctest.log
0 of 1 test suites (0 of 1 test cases) passed.

</pre>

-----
[Here is my test code.](https://github.com/cutsea110/heredoc/blob/master/test/Test.hs)

What's wrong?

**Comment by cutsea110** [comment]
I've got it.
Close this issue.

**Comment by turboMaCk** [comment]
@cutsea110 what was it? I'm also running into this error.

**Comment by turboMaCk** [comment]
For the benefit of others - my problem with wrapping too much stuff into one block it seems. I had to wrap data declaration into one `:{` ... `:}` block and usage into another.
