### ISSUE TITLE
Feature request: Assert that a property does NOT hold.

### ISSUE THREAD

**Issue by NorfairKing** [sol/doctest#147]

**Comment by andreasabel** [comment]
Can you elaborate a bit?  In particular, give an example and its intended behavior.

**Comment by NorfairKing** [comment]
We already have this:

```
prop> \ls -> length ls < 1000
```

Now I'd like:

```
notprop> \ls -> length ls >= 1000
```

Note that this is not equivalent to this:

```
prop> \ls -> not (length ls < 1000)
```

Make sure to set a deterministic seed.

**Comment by soenkehahn** [comment]
@NorfairKing, could you use [expectFailure](https://www.stackage.org/haddock/lts-10.2/QuickCheck-2.10.1/Test-QuickCheck.html#v:expectFailure) to get what you want?

**Comment by NorfairKing** [comment]
@soenkehahn Aha, Yes. (For the record, I think this function didn't exist yet when I first made my comment.)
