### ISSUE TITLE
Add --ghc-version

### ISSUE THREAD

**Issue by phadej** [sol/doctest#157]
That would be useful, as we often care which `ghc` lib version the `doctest` executable is compiled against.

The motivation is to help analysing "why it doesn't work" situations.

**Comment by sol** [comment]
For humans this is already included in `--version`.  For programmatic use I prefer `--info` (analogous to `ghc --info`, see #159).

**Comment by phadej** [comment]
Is there widely used shell scripting tools to deal with JSON data (also e.g. `Cabal` doesn't have JSON (or JSON-like) parser in it, and cannot depend on `aeson`). FWIW, GHC *also* has `--numeric-version`

**Comment by sol** [comment]
@phadej The output of `--info` can be parsed with `readMaybe`, no JSON parser required.
