### ISSUE TITLE
Forced reload makes doctests take about 10x longer

### ISSUE THREAD

**Issue by glguy** [sol/doctest#164]
doctest is timing out on our lens builds on travis. I found that this forced reload line is the culprit. It would be good to only do this reload on the broken GHCs it is necessary on.

Quoting https://github.com/ekmett/lens/issues/738#issuecomment-307581003

On my computer the tests take over 13 minutes. If I fixed doctests by removing this line linked below they take 1.5 minutes. This line appears to be a workaround for a bug in an old version of GHC.

https://github.com/sol/doctest/blob/master/src/Runner.hs#L129

**Comment by RyanGlScott** [comment]
Out of curiosity, I tried removing that line and running the tests on Travis, and [it worked without any problems](https://travis-ci.org/RyanGlScott/doctest). Locally, I also ran the tests on GHC 7.0.4, 7.2.2, and 7.4.2 (using a patched version of `mockery` to [work around a build failure](https://github.com/hspec/mockery/pull/10)), and they also worked.

**Comment by sol** [comment]
Conceptually `doctest` is horribly slow.  Running 859 simple unit tests with `hspec` takes less than 1s, yet doing the same with `doctest` takes forever.  The underlying reasons are both:

- use of the GHC API to extract haddocks
- use of `ghci` to check examples

This design decisions made sense to me when I started to work on `doctest` 8 years ago, but this approach does not scale to `lens`-size projects.

No promises, but I'm thinking about taking a different approach.
