### ISSUE TITLE
Please add a CHANGELOG

### ISSUE THREAD

**Issue by andreasabel** [sol/doctest#176]
Please add and maintain a CHANGELOG.

**Comment by sol** [comment]
@andreasabel any help with this appreciated ;).

**Comment by andreasabel** [comment]
Ah, I saw you already do maintain such a log in file CHANGES.  I think all there is todo is to rename it to CHANGELOG or CHANGELOG.md and it will be picket up by hackage automatically.

If you are fine with that, I can go ahead and implement it.

**Comment by sol** [comment]
@andreasabel I think the primary reason Hackage does not show it is because it's not listed under `extra-source-files`.  `CHANGES` may work just fine.

**Comment by andreasabel** [comment]
Ok, thanks!  I'll add it, along with the README, which could also be useful.

The way we (agda/agda) remember changes for a new release is by using github milestones to remember closed issues for a version.  Upon release, one can check whether the closed issues for a version are adequately represented in the CHANGES file.

Further, I think it makes sense that the development version is ahead of the last released version.  Thus I'll add a commit that bumps the version to 0.14.  Revert it if you disagree.

**Comment by sol** [comment]
> Further, I think it makes sense that the development version is ahead of the last released version. Thus I'll add a commit that bumps the version to 0.14. Revert it if you disagree.

It's ok with me to try this approach.

> Actually, I do not know your version policy. It could be that you wish to release 0.13.1 next. However, one can still release 0.13.1, and keep the development version at 0.14 then.

I think this is the main reason why I didn't adopt this practice yet widely.
