### ISSUE TITLE
Treating `λ` as a prompt?

### ISSUE THREAD

**Issue by kindaro** [sol/doctest#178]
Currently, `doctest` takes `>>>` to be the start of the prompt. This is a replica from `python` where the usual interpreter has this prompt by default.

I'm a haskeller, not a pythonista, and I don't like to be confused with one. So I have `λ` as my ghci prompt. I understand this is a very minor stylistic detail, but I would like to have the same `λ` as a prompt in the `doctest` declarations that I put in my code.

Maybe, if someone else likes the idea, we can band together and introduce this feature. On the downside, it means one less possible first character for the test output. But how often does one's output start with `λ`, I ask? So maybe that's no big deal.

If there happens to be some consensus, I can submit a patch in no time.

**Comment by andreasabel** [comment]
Well, if you implement a functional language in haskell, the result of a test might often be a lambda-abstraction.

I am not so enthusiastic about this proposal, since lambda is even part of the Haskell syntax.

**Comment by sol** [comment]
@kindaro First things first, thank you for your interest in `doctest` and for taking the time to open this issue.

For me this is a `wontfix`, here is some context and my reasons:

Originally, I wanted to use `ghci>` as the prompt, but back then @simonmar felt that this was too GHC specific and we settled on `>>>`.  I think `>>>` is a completely valid choice and using this syntax does not make you a pythonista (take my word for it, I've been using it multiple times and I'm still doing Haskell).

For allowing `λ` (or any other alternate prompt), I'm personally not excited about this.  Meaningful software development involves collaboration with others, and common conventions help with that.  If we now allow for alternate prompts every project that uses `doctest` has to establish their own convention and people who contribute to multiple projects have to deal with different conventions.

In addition I like to `grep` for things and allowing alternate prompts does not make this any more convenient.

Regarding `λ` specifically: I, personally, prefer to stick with Unicode code points below 128 for source code.  The only situations where I would consider to deviate from this is in string literals and comments.  Yes, GHC supports Unicode syntax, but I think, if you want "nice looking code" then that is better handled on the representation layer, e.g. with a Haskell specific font with ligatures (e.g. @i-tu's [Hasklig](https://github.com/i-tu/Hasklig)).

I acknowledge that some of the things I said are a matter of personal preference and not necessarily universally accepted across the Haskell community.  But combined it's still enough for me to close this as `wontfix`.

All that said, nothing is set in stone forever.  If there were wide community support for changing the prompt to something else I would be happy to do so and deprecate `>>>`.

**Comment by kindaro** [comment]
It is me who should thank you for the great work you are doing on this project. I completely agree with all that's been said above. I want to share some of my considerations so as to clarify the initial idea.

Concerning Unicode, my idea is that, as there is one ascii writing for equality (`==`) and one Unicode counterpart (`≡`), there may be one ascii and one Unicode writing for other things. Lambda may not be the right choice for a prompt, since it is an accepted notation for lambda abstractions, but I believe I've seen people use it for GHCi prompt (likely due to its minimality and its haskelly symbolism), and I myself eventually adopted it as well. Still, another Unicode character may be chosen.

The Unicode thing in Haskell itself appears unplanned and thus kind of haphazard, but 127 pre-defined glyphs is a laughably limited selection as well, so either choice is bad. A better abstraction will likely eventually emerge (like ligatures, but better) and, putting my hopes in that, I see any choice we can make in picking code points a poor one anyway.

Concerning conventions, my idea was to allow either one of the `>>>` and the `λ` to be used interchangeably (provided that a boolean option, like `--enable-lambda-prompt`, is set), rather than allowing any choice and thus potentially fragmenting the ecosystem big way.

I made a fork that I'll be using myself. It adds the recognition of `λ` as a prompt on top of `>>>`. It will be available [here on GitHub](https://github.com/kindaro/doctest), in case someone likes the idea as much as I do.
