### ISSUE TITLE
Add `--verbose` option that would list test cases on the screen as they are passed.

### ISSUE THREAD

**Issue by kindaro** [sol/doctest#185]
I have about a dozen of test cases in one of my projects. Sometimes I get suspicious if I mistyped something and if all the cases actually run. *(especially since, for some reason, it reports 12 successes if ran from cabal and 16 if ran manually)* So, I thought, it would be useful if there were a "verbose" option that would let me know what cases are executed, exactly.

I can submit a pull request in about a week, if there is consensus and some general advice from maintainers.

**Comment by andreasabel** [comment]
I think this is a great idea!

As a general rule, such a new feature would also have to be covered by `doctest`'s own testsuite, and be documented in the CHANGELOG and (I suppose) in the README.  :)

**Comment by kindaro** [comment]
This is actually sort of a duplicate of #132. As we solve this, we can close that other too.

**Comment by sol** [comment]
On `master`.
