### ISSUE TITLE
Writing temporary files in a doctest

### ISSUE THREAD

**Issue by Profpatsch** [sol/doctest#204]
It would be nice if doctests could create temporary files that can be used by the tests (and don’t modify the project folder).

We need to write some small `dhall` files for the doctests of the tutorial, but a naïve `writeFile` call writes to the current folder (the project folder when invoked by dhall), which could lead to actual project files being overwritten:
https://github.com/dhall-lang/dhall-haskell/pull/496#discussion-diff-199322437R174

It might make sense to `cd` to a temporary folder for doctests by default, to ensure they don’t interact with the state of the source code.

**Comment by sol** [comment]
> It would be nice if doctests could create temporary files that can be used by the tests (and don’t modify the project folder).

Technically you could do this outside of `doctest` by changing into a temporary directory and adjusting `-i`, etc accordingly.

> It might make sense to `cd` to a temporary folder for doctests by default, to ensure they don’t interact with the state of the source code.

I think it's not easy to do so.  Doctest uses the same mechanisms to resolve source files as `ghci`, e.g. guided by `-i` or implicitly assuming the current working directory.  How to find source files has to be specified by the user and is currently opaque to Doctest.  If we now change the current working directory, then that will interfere with source file resolution.

**Comment by sol** [comment]
I'm inclined to close his as `wontfix`.

**Comment by sol** [comment]
I added more detailed steps on how to achieve this to https://github.com/dhall-lang/dhall-haskell/pull/496.

Closing.
