### ISSUE TITLE
Select a particular GHC executable?

### ISSUE THREAD

**Issue by kindaro** [sol/doctest#208]
I am having trouble understanding the logic by which `doctest` chooses what GHC executable to
pick. Is it baked in at compile time? That would explain this:

    % doctest --version
    doctest version 0.16.0
    using version 8.4.3 of the GHC API
    using /home/kindaro/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/bin/ghc-8.4.3
    % which ghc
    /home/kindaro/.nix-profile/bin/ghc
    % mv /home/kindaro/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/bin/ghc-8.4.3{,.archive}
    renamed '/home/kindaro/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/bin/ghc-8.4.3' -> '/home/kindaro/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/bin/ghc-8.4.3.archive'
    % doctest --version
    doctest version 0.16.0
    using version 8.4.3 of the GHC API
    using /home/kindaro/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/bin/ghc-8.4.3
    % doctest Test.hs
    doctest: /home/kindaro/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/bin/ghc-8.4.3: getPermissions:getFileStatus: does not exist (No such file or directory)

From the above, it appears that `doctest` does not even bother looking at `$PATH`. So, there is no way to choose one of several available compiler versions that I have stashed here and there.

Some of my works demand that I use GHC 8.6, but many packages _(including, at the moment, `doctest` itself)_ only support GHC 8.4. So, it appears to be beneficial to be able to select a `ghc` executable that is desired to be used, for each particular test run.

I propose, to this end, that we add a command line option and/or a feature to respect the `$PATH` environment variable.

**Comment by sol** [comment]
> I am having trouble understanding the logic by which `doctest` chooses what GHC executable to
pick.

`doctest` uses `ghc-paths` to find the `ghc` executable.

> Some of my works demand that I use GHC 8.6, but many packages (including, at the moment, doctest itself) only support GHC 8.4.

We have https://github.com/sol/doctest/issues/207 for GHC 8.6 support.  Please feel free to help make this happen.

> I propose, to this end, that we add a command line option and/or a feature to respect the $PATH environment variable.

`doctest` uses both the `ghc` executable as well as the GHC API.  The two versions have to match, for that reason we cannot change the used `ghc` executable at runtime.

`doctest` can only be used with the version of `ghc` it was compiled with.

I'm closing this as `wontfix`.
