### ISSUE TITLE
Test failure in `doctest-0.16.0.1`

### ISSUE THREAD

**Issue by coot** [sol/doctest#213]
```
  test/RunSpec.hs:84:5:
  1) Run.doctest respects HASKELL_PACKAGE_SANDBOX
       uncaught exception: IOException of type NoSuchThing
       cabal: rawSystem: runInteractiveProcess: exec: does not exist (No such file or director
y)

  To rerun use: --match "/Run/doctest/respects HASKELL_PACKAGE_SANDBOX/"
```

**Comment by quasicomputational** [comment]
Thanks for the report.

What OS is this on? And how exactly are you running the tests?

**Comment by coot** [comment]
I am running `GNU/Gentoo` but I run into the problem when compiling another package with `nix` which pulled `doctest` as a dependency.  I think the `nix` environment needs some binary.  Do you have any idea what is missing?

**Comment by quasicomputational** [comment]
Here's what that test does:

```
    it "respects HASKELL_PACKAGE_SANDBOX" $ do
      withCurrentDirectory "test/integration/custom-package-conf/foo" $ do
        ExitSuccess <- rawSystem "ghc-pkg" ["init", "../packages"]
        ExitSuccess <- rawSystem "cabal" ["configure", "--disable-optimization", "--disable-library-profiling", "--package-db=../packages"]
        ExitSuccess <- rawSystem "cabal" ["build"]
        ExitSuccess <- rawSystem "cabal" ["register", "--inplace"]
        return ()
```

So if you don't have `cabal`, `ghc-pkg` or `ghc` (because that's going to be invoked by Cabal) available in the environment that the test's running in, that would be a plausible source of the error.

**Comment by coot** [comment]
Yes, that's likely the problem.  I'll try to fix a nix expression.  I'll close this since I don't think this is an issue with `doctest`; thanks for help!
