### ISSUE TITLE
Trouble with missing packages when run in Nix shell

### ISSUE THREAD

**Issue by evanrelf** [sol/doctest#253]
#### What's the problem?

I have a Haskell project, built with Nix, that includes doctests. When I run `doctest` in my Nix shell (generated by `cabal2nix`), `doctest` fails to run tests because it can't find my dependencies.

#### Why is this happening?

I've determined that this is because `doctest` is not using the GHC in my `$PATH`, which includes all my project's dependencies in its package database. Instead it is using the GHC it was compiled with; `doctest` uses the version of GHC it was compiled with, not the one in my `$PATH`, because it's using a hard-coded path provided by `ghc-paths` that was baked in at compile time.\

#### How can I fix this?

I'm able to overcome this issue by preparing a hand-crafted `.ghc.environment.*` file to configure `doctest`'s GHC at runtime without access to its command-line arguments – telling it to use the package database from the GHC in my `$PATH`, not its own internal one – but that's just a frustrating and unintuitive band-aid.

For some reason which I haven't figured out yet, `doctest` works fine when run during the Nix build process (via `nix-build`).

#### Next steps

Could anyone enlighten me on why this works when run with `nix-build`, but not when run in a Nix shell? (cc. @peti since they had valuable insight in this related issue: https://github.com/sol/doctest/issues/115)

If this is actually a problem, and I haven't missed some important detail, would it be possible to add an optional command-line flag to `doctest` to specify the path to your desired GHC at runtime?

**Comment by evanrelf** [comment]
I was able to work around this more elegantly by specifying the following in my Haskell derivation's `shellHook`:
```
export HASKELL_PACKAGE_SANDBOXES="$NIX_GHC_LIBDIR/package.conf.d"
```

After reading this https://github.com/sol/doctest/blob/1cc1902b602ed3c6cf9a1c8c2144acb27435dc17/src/PackageDBs.hs#L58-L92, I found that `doctest` loads package databases from certain environment variables. `GHC_PACKAGE_PATH` would also work, except Cabal doesn't like when it's set (the generic Haskell builder in Nix has to work around this by setting it and unsetting it at different points). Since `doctest` also offers the `HASKELL_PACKAGE_SANDBOXES` variable, which doesn't irritate Cabal, I'm using that.

**Comment by quasicomputational** [comment]
`doctest` is quite intimately bound to GHC; it -has- to use the one it's compiled with.

As for hooking up `doctest` to the package database so it can find dependencies, the current state of the art is to use [`cabal-doctest`](http://hackage.haskell.org/package/cabal-doctest). It's a hack, but it's a hack that works.
