### ISSUE TITLE
GHC 9.0 and cabal-install 3.4

### ISSUE THREAD

**Issue by quasicomputational** [sol/doctest#275]
GHC 9.0 is upon us; [the first alpha was announced on Monday](https://mail.haskell.org/pipermail/ghc-devs/2020-September/019286.html). And it's been released!

Here's a rough list of what's needed for a doctest release for GHC 9.0, most of which is waiting for things to happen:

* [x] Releases:
  * [x] GHC 9.0
  * [x] cabal-install 3.4

* [x] cabal-install has dropped support for sandboxes. I am just going to rip out doctest's integration with them. AFAIK, they're obsoleted by Stack and cabal-install's v2 ('Nix-style') commands, depending on preference. Still, this will be a breaking change.

     This isn't blocked on anything, and getting ahead of the game with the breaking release earlier rather than later might make the transition easier (rather than entangling it with the GHC 9.0 transition), so that's what I am intending to do.

* [x] doctest has adapted to the breaking changes in GHC 9.0's API.

* [x] CI business
  * [x] Package availability:
    * [x] GHC 9.0
    * [x] cabal-install 3.4
  * [x] GHC 9.0 row added
  * [x] No `allow-newer`
  * [x] Not an allowed failure

* [x] All dependencies are ready. Known blockers:
  * [x] `ghc-paths` - bounds only?
  * [x] `hsc2hs` - bounds only, just waiting on a release?
  * [x] `QuickCheck` - code change needed; nick8325/quickcheck#314
  * [x] `syb` - code change needed; dreixel/syb#25

**Comment by andreasabel** [comment]
I am currently working on the following, expect a PR with many `#if`s soon.
> doctest has adapted to the breaking changes in GHC 9.0's API.

**Comment by andreasabel** [comment]
> ... expect a PR ... soon.

"soon" ;-D  (Didn't expect wrestling with CPP not screaming on `#elsif` instead of `#elif`, with subtle test-suite failures, with mysteries of the build process of doctest, haha.)

Anyway, PR #295 should fix the remaining open points for this issue.

**Comment by andreasabel** [comment]
Released 0.18.1!
