### ISSUE TITLE
doctest dependencies

### ISSUE THREAD

**Issue by StevenXL** [sol/doctest#297]
Hi folks,

I have a project that has `doctest` as a dependency, but it is failing to build:

```
attoparsec                > Registering library for attoparsec-0.13.2.5..
Progress 41/239            

--  While building package doctest-0.16.3 (scroll up to its section to see the error) using:
      /home/steven/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.4 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

I had a very similar problem with [another package](https://github.com/kowainik/issue-wanted/issues/81), which was resolved by adding a system library via `apt install libpq-dev`. Is there an equivalent solution here?

**Comment by andreasabel** [comment]
@StevenXL wrote:
> I had a very similar problem with [another package](https://github.com/kowainik/issue-wanted/issues/81), which was resolved by adding a system library via `apt install libpq-dev`. Is there an equivalent solution here?

I do not think these problems are related.

Unfortunately, your bug report does not contain enough context to give a chance to reproduce your problem.  Does the problem persist?  If yes, please come back with more information...

**Comment by andreasabel** [comment]
Ok good, I take that the problem resolved itself.
