### ISSUE TITLE
Incompatible with markdown-unlit?

### ISSUE THREAD

**Issue by turion** [sol/doctest#299]
I tried the following minimal file:

    ```haskell
    -- |
    -- >>> 23
    -- 23
    main :: IO ()
    main = do
      putStrLn "hi"
    ``` 

I saved it as `README.md`, symlinked it to `README.lhs` and then tried:

`doctest README.lhs -pgmL markdown-unlit`

Unfortunately this says: 
```
README.lhs:5:1: error: parse error on input ‘main’
  |
5 | main :: IO ()
  | ^^^^
```

I don't believe this to be an actual syntax error since posting the same docs in a regular file doesn't result in a parse error.

**Comment by sol** [comment]
@turion if you change your code to

```haskell
module Foo where
-- |
-- >>> 23
-- 23
main :: IO ()
main = do
  putStrLn "hi"
```
It will work.

This is a Haddock bug.

Try:
```
 haddock --optghc=-pgmLmarkdown-unlit README.lhs
```
This will fail with the same error.

@turion please report this as an upstream bug?
