### ISSUE TITLE
I could discuss if you wouldn't limit discussion.

### ISSUE THREAD

**Issue by phadej** [sol/doctest#323]
> PS: @phadej just to be very clear, I did not accuse you of anything. If you want to help I'm happy to have a discussion at cabal/cabal on how to minimize breakage of hpack due to cabal requiring users to list Paths_* under autogen-modules.

Don't use `cabal-version` which requires that. Or if you use, then what prevents `hpack` of adding `Paths_*` to `autogen-modules`. Sorry, I don't understand the problem.

**Comment by sol** [comment]
Fixed in `hpack-0.34.6`.
