### ISSUE TITLE
How to pass `--fast` when going via `cabal repl`?

### ISSUE THREAD

**Issue by andreasabel** [sol/doctest#395]
I tried e.g. this:
```
cabal  repl -w doctest --repl-options=-Wno-type-defaults --doctest-options=--fast
```
This does not give an error, so presumably `cabal repl` accepted `--doctest-options`.
However, it does not have any observable effect.  I can also write:
```
cabal  repl -w doctest --repl-options=-Wno-type-defaults --doctest-options=--KreizBirnbaumUnHollerstaun
```
and no error is raised.

My experience suggest that the content of `--doctest-options` is just zapped somewhere.

So then, @sol, how do I pass `--fast` to `doctest`?

**Comment by sol** [comment]
@andreasabel with `cabal  repl --with-ghc=doctest`, if you want to pass additional arguments to `doctest` then you need to use `--repl-options`.

However, `doctest-0.20.*` does not accept `doctest`-specific options when invoked via `cabal repl`.  https://github.com/sol/doctest/pull/397 / `doctest-0.21.0` lifts that restriction.
