### ISSUE TITLE
Support GHC 9.10

### ISSUE THREAD

**Issue by andreasabel** [sol/doctest#420]
https://github.com/BNFC/bnfc/actions/runs/9127670093/job/25098437386?pr=482#step:20:25
> [__0] trying: doctest-0.22.2 (user goal)
> [__1] rejecting: ghc-9.10.1/installed-69c3 (conflict: doctest => ghc>=8.0 && <9.10)

**Comment by sol** [comment]
@andreasabel can you do a Hackage revision?

**Comment by andreasabel** [comment]
> @andreasabel can you do a Hackage revision?

Sure, if this is all that is needed.

**Comment by andreasabel** [comment]
Build locally.  Revision 1 at https://hackage.haskell.org/package/doctest-0.22.2/revisions/
