### ISSUE TITLE
tests fails with GHC 7.8

### ISSUE THREAD

**Issue by kazu-yamamoto** [sol/doctest#76]
Now `cabal test` on doctest-haskell got the following error:

``` shell
17) Property.runProperty reports the values for which a property that takes multiple arguments fails
expected: ["False","0","\"\""]
 but got: ["<interactive>:24:66:","    \8216doctest_prop\8217 is not in the type environment at a reify","    In the splice: $(polyQuickCheck 'doctest_prop)"]
```

This is relating to src/Property.hs:

``` haskell
  where
    quickCheck term vars =
      "let doctest_prop " ++ unwords vars ++ " = " ++ term ++
      " in $(polyQuickCheck 'doctest_prop)"
```

It seems to me that the behavior of Template Haskell changed. I don't know how to fix this.

**Comment by gelisam** [comment]
Google let me here after encountering one of the error messages quoted above:

    <interactive>:39:3:
        Not in scope: ‘polyQuickCheck’
        In the splice: $(polyQuickCheck (mkName "doctest_prop"))
    
    <interactive>:39:3:
        GHC stage restriction:
          ‘polyQuickCheck’ is used in a top-level splice or annotation,
          and must be imported, not defined locally
        In the expression: polyQuickCheck (mkName "doctest_prop")
        In the splice: $(polyQuickCheck (mkName "doctest_prop"))

The solution (which wasn't immediately clear from this thread) was to perform a `cabal install QuickCheck` before executing doctest.
