### ISSUE TITLE
Make sure that Paths_*, etc. are found by default

### ISSUE THREAD

**Issue by sol** [sol/doctest#89]
Should we add `-idist/build/autogen` by default?

**Comment by andreasabel** [comment]
See also what https://github.com/haskellari/cabal-doctest can offer to the problems described here.

**Comment by quasicomputational** [comment]
Closing on the same basis as #127.

**Comment by steve-chavez** [comment]
One workaround is making your function not depend on `Paths_*` (instead add it as a parameter). I think it makes sense to make the function pure for the doctest.

**Comment by sol** [comment]
@steve-chavez please refer to the README on how to do things properly.

https://github.com/sol/doctest#running-doctest-for-a-cabal-package
