### ISSUE TITLE
Support Python doctest syntax for multi-line examples

### ISSUE THREAD

**Issue by kaoskorobase** [sol/doctest#91]
It would be nice if doctest could support multi-line examples with the [syntax supported by Python's doctest](https://docs.python.org/2/library/doctest.html#how-are-docstring-examples-recognized):

```
>>> get systemIncludes
...   $ append systemIncludes ["path1"] . append systemIncludes ["path2"]
...   $ mempty
["path2","path1"]
```

These examples would not be directly pastable to ghci, but it would look a much nicer typographically (this is subjective, of course) than this example from [one of my packages](https://hackage.haskell.org/package/shake-language-c-0.5.0/docs/Development-Shake-Language-C-BuildFlags.html):

```
>>> :{
  get systemIncludes
    $ append systemIncludes ["path1"] . append systemIncludes ["path2"]
    $ mempty
:}
["path2","path1"]
```

**Comment by andreasabel** [comment]
I suppose doctest should stay in sync with haddock.

This request looks abandoned, close?

**Comment by kaoskorobase** [comment]
Yes, sorry, didn't have the time to follow up :)
