### ISSUE TITLE
Doctest and literate haskell?

### ISSUE THREAD

**Issue by FrankDMartinez** [sol/doctest#92]
I took the Fibonacci example and turned it into literate Haskell. Doctest rejected the file with:

`fib.lhs line 7: unlit: Program line next to comment`
`fib.lhs line 10: unlit: Program line next to comment`
`fib.lhs line 12: unlit: Program line next to comment`
`doctest: doctest: phase 'Literate pre-processor' failed (exitcode = 1)`

Does doctest support literate Haskell?

**Comment by elviejo79** [comment]
@FranklinChen  Give that I write the doctests as you suggest.
How do you execute them?


If I write my code as you suggest
```haskell
> -- | Compute Fibonacci numbers
> -- Examples:
> --
> -- >>> fib 10
> -- 55
> --
> -- >>> fib 5
> -- 5
```
Then I try to execute it
```shell
$ doctest Fibonacci.lhs                                                                       
Examples: 0  Tried: 0  Errors: 0  Failures: 0        
```
No tests get executed...

Any suggestions?

**Comment by FranklinChen** [comment]
It works for me. The file I have:

```haskell
> module Fib where

> -- | Compute Fibonacci numbers
> -- Examples:
> --
> -- >>> fib 10
> -- 55
> --
> -- >>> fib 5
> -- 5

> fib :: Int -> Int
> fib 0 = 0
> fib 1 = 1
> fib n = fib (n - 1) + fib (n - 2)
```
