### ISSUE TITLE
Cabal & doctest integration

### ISSUE THREAD

**Issue by bitemyapp** [sol/doctest#97]
A `cabal doctest` or some manner of Cabal auto-magic is needed.

Should do discovery and running of doctests automatically.

It's *extremely* hard for people to get doctests working with a Cabal project. It took be 3 days, 10-12 hours apiece just to get doctests working for [Bloodhound](https://github.com/bitemyapp/bloodhound). Now I realize I'm a fucking moron, but I was also getting help in IRC from people like @ekmett who uses doctests for `lens` and he had no idea what was causing things to break either.

The things that make doctests hard to use fall into three categories:

1. Cabal project/sandbox awareness

2. Custom Setup.hs for doctest discovery and execution

3. Insanely finicky doctest syntax and interactions with Haddock

This notion fixes 1 and 2, but not 3. However, if users have the reasonable belief that 1 and 2 are okay and should be working, they'll spend less time trying to diagnose the wrong things when they've messed up number 3.

I filed this issue long after having gotten Bloodhound's doctest integration working because I ran into somebody I know on IRC struggling for multiple days with this again.

I'm tired of having to tell people to copy-paste what I have in Bloodhound to make it work and people hate having to cargo-cult this anyway. Doctests have caused problems for the [NICTA course](https://github.com/NICTA/course) as well.

**Comment by sol** [comment]
@bitemyapp That is a good point.  I think if we want `cabal doctest`, then it may make sense to open an issue for https://github.com/haskell/cabal/.

I would be more that happy to see somebody working on this (implementation may be very similar to what we have for `cabal haddock`).

**Comment by bitemyapp** [comment]
@sol I'll migrate this accordingly. Thank you.
