### ISSUE TITLE
Guess right sandbox pkg-db path on GHC version mismatch

### ISSUE THREAD

**Issue by DanielG** [sol/doctest#99]
If cabal.sandbox.config contains a "package-db:" declaration with the
wrong path and only the ghc version is wrong, for example:

```
package-db: <DIR>/.cabal-sandbox/x86_64-linux-ghc-7.8.3-packages.conf.d
```

Even though I'm using 7.10.0.20141222 `cabal repl` will correct
this and pass

```
-package-db <DIR>/.cabal-sandbox/x86_64-linux-ghc-7.10.0.20141222-packages.conf.d
```

to ghci. 

Obviously Cabal/cabal-install is doing some magic. This is paticularily annoying when jumping between different ghc versions for testing as `cabal sandbox init` using the new compiler won't touch cabal.sandbox.config if it already exists even though the package-db path is wrong.

I fixed this in ghc-mod using this commit https://github.com/DanielG/ghc-mod/commit/777229ebbc886deec09a60932784400856e89799#diff-2b460056ea1f03da424528e5c09aa5c2R126 maybe doctest should be doing something simmilar?

I haven't actually been able to find the code that is responsible for this guessing in Cabal so I'm not sure weather it only fixes the compiler version or the arch also, ghc-mod just replaces the last component of the path but I'm not sure what is correct.

**Comment by DanielG** [comment]
Oh and do note that the referenced commit is not 100% correct yet (so don't copy the code there), see https://github.com/DanielG/ghc-mod/pull/3

**Comment by quasicomputational** [comment]
Sandboxes are on their way out, so I'm going to go ahead and close this as 'won't ever get done'.
